# permissions for end users to view alluxioruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alluxioruntime-viewer-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes/status
  verbs:
  - get
