# permissions for end users to edit alluxioruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alluxioruntime-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes/status
  verbs:
  - get
