# permissions for end users to edit databackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databackup-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - databackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - databackups/status
  verbs:
  - get
