# permissions for end users to view goosefsruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goosefsruntime-viewer-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes/status
  verbs:
  - get
