# permissions for end users to edit goosefsruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goosefsruntime-editor-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes/status
  verbs:
  - get
