
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - alluxioruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - databackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - databackups/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - databackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - dataloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - dataloads/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - dataloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - datasets/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - goosefsruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - jindoruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - jindoruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - jindoruntimes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - juicefsruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - juicefsruntimes/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - juicefsruntimes/status
  verbs:
  - get
  - patch
  - update
