
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - data.fluid.io
  resources:
  - datasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.fluid.io
  resources:
  - datasets/finalizers
  verbs:
  - update
- apiGroups:
  - data.fluid.io
  resources:
  - datasets/status
  verbs:
  - get
  - patch
  - update
